apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exportarr-sabnzbd
  namespace: media-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: exportarr-sabnzbd
      component: metrics
  namespaceSelector:
    matchNames:
      - media-monitoring
  endpoints:
    - port: metrics
      path: /metrics
