apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-pat
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: arc-github-pat
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: arc-github-pat
