{
 "title": "ARC Autoscaling Runner Set Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SystemNamespace",
    "label": "ARC System Namespace",
    "query": {
     "query": "label_values(gha_controller_running_listeners,namespace)"
    }
   },
   {
    "name": "Scaleset",
    "label": "Scale Set",
    "query": {
     "query": "label_values(gha_desired_runners,repository)"
    }
   },
   {
    "name": "RunnerNamespace",
    "label": "Runner Namespace",
    "query": {
     "query": "label_values(gha_desired_runners{repository=~\"$Scaleset\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Runner Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup Duration",
   "type": "heatmap",
   "description": "Heat map showing the typical time before a job starts and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_startup_duration_seconds_bucket{repository=~\"$Scaleset\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "heatmap",
   "description": "Heat map showing the typical time to complete a job and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_execution_duration_seconds_bucket{repository=~\"$Scaleset\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Desired Runners",
   "type": "gauge",
   "description": "Number of runners desired by the scale set",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_desired_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assigned Jobs",
   "type": "gauge",
   "description": "The number of jobs assigned to the scale set.  The threshold is triggered with the number of assigned jobs exceeds the number of desired runners. This indicates that not all jobs will have an available runner.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_assigned_jobs{namespace=~\"$RunnerNamespace\", repository=~\"$Scaleset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gha_desired_runners{namespace=~\"$RunnerNamespace\", repository=~\"$Scaleset\"}) + 1",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "gauge",
   "description": "The number of workflow jobs currently executing",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_assigned_jobs{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "timeseries",
   "description": "The sum of the reads and writes occurring within the runner namespace.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Idle Runners",
   "type": "gauge",
   "description": "Number of registered runners that do not have assigned jobs.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_idle_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Runners",
   "type": "gauge",
   "description": "Number of runner pods that are waiting to be created. When this number exceeds the number of pods Kubernetes reports as Waiting, it indicate cluster performance issues.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_pending_ephemeral_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Runners",
   "type": "gauge",
   "description": "The number of runners in a failed state. These runners are typically misconfigured and count against the scale set's maximum limit.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_failed_ephemeral_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Memory",
   "type": "gauge",
   "description": "The peak memory used by a container in a given scale set's namespace.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$RunnerNamespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out of Memory",
   "type": "stat",
   "description": "The number of containers that are reporting that they were terminated by an out-of-memory condition (OOMK.iller)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",namespace=~\"$RunnerNamespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "stat",
   "description": "The number of active scale set listeners",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_running_listeners{namespace=~\"$SystemNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Running Jobs by Scale Set",
   "type": "table",
   "description": "Scale sets currently running jobs. Only shows scale sets with at least one active job.",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "gha_assigned_jobs{namespace=~\"$RunnerNamespace\", repository=~\"$Scaleset\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Pod Status",
   "type": "bargauge",
   "description": "The Kubernetes-reported pod status.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_idle_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(gha_busy_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"}) or on() vector(0)",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(gha_controller_pending_ephemeral_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"}) or on() vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(gha_controller_failed_ephemeral_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"}) or on() vector(0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Controller Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconcile Time",
     "type": "timeseries",
     "description": "The average time required for a reconciliation request to be processed. This reflects the time required for the controller to process a single request to modify a Kubernetes resource.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"$SystemNamespace\"}[$__rate_interval])",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Workqueue Queue Duration",
     "type": "timeseries",
     "description": "The average time a queued reconciliation request spends waiting to be processed.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(workqueue_queue_duration_seconds_sum{namespace=\"$SystemNamespace\"}[$__rate_interval])",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconciliation Errors",
     "type": "timeseries",
     "description": "Errors indicate that controller has not achieved a desired state and is requesting Kubernetes to queue another request for reconciliation. Ideally, this number remains close to zero. An increasing number can indicate resource contention or delays processing API server requests.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_errors_total{namespace=\"$SystemNamespace\"}[$__rate_interval])",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "API Calls",
     "type": "timeseries",
     "description": "The number of calls to the API server",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "targets": [
      {
       "expr": "sum by (method, code) (rate(rest_client_requests_total{namespace=\"$SystemNamespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue Depth",
     "type": "stat",
     "description": "The number of reconcile requests that are waiting to be processed by the controller. A growing queue depth can indicate that the Kubernetes API Server or the controller does not have enough resources. This can lead to pods taking longer to be deleted or started. ",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum (workqueue_depth{namespace=\"$SystemNamespace\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Workers",
     "type": "stat",
     "description": "The number of workers that are currently being used to process reconcile requests. Increasing this number can reduce the work queue duration, but each new worker adds a small amount of time due to context switching.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (controller) (controller_runtime_active_workers)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Runner Throughput & Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Registered Runners",
   "type": "stat",
   "description": "Runners currently registered with GitHub Actions.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_registered_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs (Actual)",
   "type": "stat",
   "description": "Jobs actively running on runners right now.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_running_jobs{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Runners",
   "type": "stat",
   "description": "Configured minimum number of idle runners.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_min_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Runners",
   "type": "stat",
   "description": "Configured maximum number of runners.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_max_runners{repository=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Success Rate",
   "type": "stat",
   "description": "Percentage of completed jobs that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gha_completed_jobs_total{repository=~\"$Scaleset\", job_result=\"success\"}[$__rate_interval])) / sum(rate(gha_completed_jobs_total{repository=~\"$Scaleset\"}[$__rate_interval])) * 100",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Job Start Rate",
   "type": "timeseries",
   "description": "Rate of jobs starting per scale set over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(repository) (rate(gha_started_jobs_total{repository=~\"$Scaleset\"}[$__rate_interval]))",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Completed Jobs by Result",
   "type": "timeseries",
   "description": "Rate of completed jobs broken down by result (success, failure, cancelled, etc.).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job_result) (rate(gha_completed_jobs_total{repository=~\"$Scaleset\"}[$__rate_interval]))",
     "legendFormat": "{{job_result}}"
    }
   ]
  }
 ]
}