apiVersion: v1
kind: Service
metadata:
  name: matchexec-lb
  namespace: matchexec
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.1.20.203"
    kube-vip.io/ignore: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: matchexec
    app.kubernetes.io/instance: matchexec
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
