{
 "title": "UniFi-Poller: USG Insights - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays detailed information for security gateways in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller",
  "usg"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_device_info{type=~\"udm|usg|ugw|uxg\"},source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_device_info{source=~\"$Controller\", type=~\"udm|usg|ugw|uxg\"},site_name)"
   },
   {
    "name": "Gateway",
    "query": "label_values(unpoller_device_info{site_name=~\"$Site\", type=~\"udm|usg|ugw|uxg\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Gateway Details",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_info{site_name=~\"$Site\", name=~\"$Gateway\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"})"
    }
   ]
  },
  {
   "title": "Site: $Site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Site",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Uptime"
      }
     ]
    },
    {
     "title": "Speed Test",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_speedtest_upload{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Upload"
      },
      {
       "expr": "unpoller_device_speedtest_download{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Download"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 9, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (unpoller_device_speedtest_runtime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})",
       "legendFormat": "{{name}} Test Time"
      },
      {
       "expr": "sum by (name) (unpoller_device_uplink_latency_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})",
       "legendFormat": "{{name}} Uplink Latency"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_cpu_utilization_ratio{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} CPU %"
      },
      {
       "expr": "unpoller_device_memory_utilization_ratio{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} RAM %"
      }
     ]
    },
    {
     "title": "Uplink",
     "type": "singlestat",
     "description": "WAN Port Speed",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_uplink_speed_mbps{site_name=~\"$Site\", name=~\"$Gateway\"}"
      }
     ]
    },
    {
     "title": "Desktop",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"desktop\"}"
      }
     ]
    },
    {
     "title": "Users",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"user\"}"
      }
     ]
    },
    {
     "title": "Mobile",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"mobile\"}"
      }
     ]
    },
    {
     "title": "Guests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"guest\"}"
      }
     ]
    },
    {
     "title": "Handheld",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"handheld\"}"
      }
     ]
    },
    {
     "title": "USG Load Average",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "unpoller_device_load_average_1{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} load1"
      },
      {
       "expr": "unpoller_device_load_average_15{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} load15"
      }
     ]
    },
    {
     "title": "WAN Throughput",
     "type": "graph",
     "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Tx"
      }
     ]
    },
    {
     "title": "LAN Throughput",
     "type": "graph",
     "description": "Spikes on this graph that do not appear on the WAN graph indicate inter-VLAN-routing. Rx is on the negative axis.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Rx"
      },
      {
       "expr": "rate(unpoller_device_lan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Tx"
      }
     ]
    },
    {
     "title": "WAN Packets",
     "type": "graph",
     "description": "PPS on the WAN interface. Rx is on the negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_receive_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Tx"
      }
     ]
    },
    {
     "title": "LAN Packets",
     "type": "graph",
     "description": "PPS on the LAN interface. Rx is on the negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Rx"
      },
      {
       "expr": "rate(unpoller_device_lan_transmit_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Tx"
      }
     ]
    },
    {
     "title": "WAN Multicast & Broadcast",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_transmit_broadcast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Broadcast Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_broadcast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Broadcast Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_multicast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}}  Multicast Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_multicast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Multicast Tx"
      }
     ]
    },
    {
     "title": "WAN Drops & Errors",
     "type": "graph",
     "description": "May show problems with your WAN interface. Rx on negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_transmit_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Drops Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Drops Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_errors_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Errors Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_errors_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Errors Rx"
      }
     ]
    },
    {
     "title": "LAN Drops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Dropped Rx"
      }
     ]
    }
   ]
  },
  {
   "title": "Purposely Empty Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  }
 ]
}
{
 "title": "UniFi-Poller: UAP Insights - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays detailed information for wireless access points in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "uap",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_device_info{type=\"uap\"},source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_device_info{source=~\"$Controller\", type=\"uap\"},site_name)"
   },
   {
    "name": "AP",
    "label": "UniFi AP:",
    "query": "label_values(unpoller_device_info{site_name=~\"$Site\", type=~\"uap|udm\",model!=\"UDMPRO\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "content": "<br>\n<br>\n<center><b><font size=\"6px\">Unifi UAP</font></b></center>\n"
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (channel) (unpoller_client_roam_count_total{site_name=~\"$Site\", ap_name=~\"$AP\"})\n",
     "legendFormat": "Ch {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (radio_desc) (unpoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_desc}}"
    }
   ]
  },
  {
   "title": "Client / MAC OUI",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective.",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (oui) (unpoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
     "legendFormat": "e {{oui}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(unpoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"user\"})"
    }
   ]
  },
  {
   "title": "Guests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(unpoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"guest\"})"
    }
   ]
  },
  {
   "title": "Access Point Details",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unpoller_device_info{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unpoller_device_bytes_total{site_name=~\"$Site\", name=~\"$AP\"})"
    }
   ]
  },
  {
   "title": "Networks / UAP",
   "type": "table-old",
   "description": "The counters in this table represent uptime totals and do not change with the time range selector. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_ccq_ratio{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_average_client_signal{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_receive_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_transmit_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_transmit_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_receive_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_receive_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unpoller_device_vap_transmit_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    }
   ]
  },
  {
   "title": "UAP CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_cpu_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UAP Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory Utilization" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_memory_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UAP Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_load_average_1{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} load1"
    },
    {
     "expr": "unpoller_device_load_average_15{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} load15"
    }
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_stations{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} users"
    }
   ]
  },
  {
   "title": "Wireless Traffic / Vendor",
   "type": "graph",
   "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (unpoller_client_receive_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
     "legendFormat": "{{oui}} Rx"
    },
    {
     "expr": "sum (unpoller_client_transmit_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
     "legendFormat": "{{oui}} Tx"
    }
   ]
  },
  {
   "title": "Users & Guests / Radio Band",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (unpoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by  (radio,name)",
     "legendFormat": "{{name}} Guests 2,4GHz"
    },
    {
     "expr": "sum (unpoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
     "legendFormat": "{{name}} Users  2.4GHz"
    },
    {
     "expr": "sum (unpoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
     "legendFormat": "{{name}} Users 5GHz"
    },
    {
     "expr": "sum (unpoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by (radio,name)",
     "legendFormat": "{{name}} Guests 5GHz"
    }
   ]
  },
  {
   "title": "Average AP Client Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "dBm", "label": "Average Client Signal" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_vap_average_client_signal{name=~\"$AP\"}",
     "legendFormat": "{{name}} {{vap_name}} {{radio}}"
    }
   ]
  },
  {
   "title": "Average AP Client RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "dBm", "label": "Average Client RSSI" }
   ],
   "targets": [
    {
     "expr": "avg(unpoller_client_rssi_db{ap_name=~\"$AP\"}) by (ap_name, radio_name)",
     "legendFormat": "{{ap_name}}  {{radio_name}}"
    }
   ]
  },
  {
   "title": "5 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CCQ % / VAP" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"na\"}",
     "legendFormat": "{{name}} {{vap_name}}"
    }
   ]
  },
  {
   "title": "2.4 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CCQ % / VAP" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"ng\"}",
     "legendFormat": "{{name}} {{vap_name}}"
    }
   ]
  },
  {
   "title": "5 GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_radio_channel_utilization_receive_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "unpoller_device_radio_channel_utilization_transmit_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  {
   "title": "2.4 GHz Channel Utilization",
   "type": "graph",
   "description": "Displays 2.4GHz usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_radio_channel_utilization_receive_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} {{radio}} Rx"
    },
    {
     "expr": "unpoller_device_radio_channel_utilization_transmit_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} {{radio}} Tx"
    }
   ]
  },
  {
   "title": "5 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}}  Rx"
    }
   ]
  },
  {
   "title": "2.4 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Rx"
    }
   ]
  },
  {
   "title": "5 GHz Packets",
   "type": "graph",
   "description": "PPS on the na band. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "pps", "label": "PPS" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Out"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} In"
    }
   ]
  },
  {
   "title": "2.4 GHz Packets",
   "type": "graph",
   "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "pps", "label": "PPS" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Out"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} In"
    }
   ]
  },
  {
   "title": "5 GHz Drops/Errors",
   "type": "graph",
   "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_receive_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_crypts_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Crypts Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_frags_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Frags Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_nwids_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Nwids Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_retries_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Retries Tx"
    }
   ]
  },
  {
   "title": "2.4 GHz Drops/Errors",
   "type": "graph",
   "description": "In is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unpoller_device_vap_receive_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Tx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_crypts_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Crypts Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_frags_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Frags Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_receive_nwids_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Nwids Rx"
    },
    {
     "expr": "sum (rate(unpoller_device_vap_transmit_retries_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Retries Tx"
    }
   ]
  }
 ]
}
{
 "title": "UniFi-Poller: Client Insights - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays detailed information for clients in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_client_uptime_seconds,source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_client_uptime_seconds{source=~\"$Controller\"},site_name)"
   },
   {
    "name": "AP",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\"},ap_name)"
   },
   {
    "name": "Switch",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\"},sw_name)"
   },
   {
    "name": "Wireless",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\", wired=\"false\"},name)"
   },
   {
    "name": "Wired",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\", sw_name=~\"$Switch\", wired=\"true\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" },
   { "name": "Identifier", "query": "name, name\\,mac" }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table-old",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    }
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table-old",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_uptime_seconds{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_receive_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_transmit_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (hostname) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (radio_proto) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (oui) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": " w {{oui}}"
    },
    {
     "expr": "count by (oui) (+unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "e  {{oui}}"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "graph",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "graph",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Rx is on the negative axis. Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth / Echos & FireTVs",
   "type": "graph",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\"^amazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\"^amazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\"^amazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\"^amazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Cameras",
   "type": "graph",
   "description": "Cameras TX / RX bytes per second. Rx is on the negative axis. This graph shows any device with the word \"camera\" in its name and has nothing to do with UniFi Protect/video products. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{ap_name=~\"$AP\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{ap_name=~\"$AP\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{sw_name=~\"$Switch\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{sw_name=~\"$Switch\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "dB", "label": "RSSI Quality" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_rssi_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_signal_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "dB", "label": "Noise" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_noise_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "graph",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Attempts / Second" }
   ],
   "targets": [
    {
     "expr": "avg by ($Identifier) (rate(unpoller_client_wifi_attempts_transmit_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "graph",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_receive_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "Tx Retries / Second" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_retries_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "dBm", "label": "Transmit Power dBm" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_power_dbm{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Anomalies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Anomalies" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_anomalies{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Satisfaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "Client Satisfaction" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_satisfaction_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Roam Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Roam Count" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_roam_count_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Connection Quality %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "percentunit", "label": "CCQ" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_ccq_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  }
 ]
}