apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: degoog-secrets
  namespace: degoog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: degoog-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: settings-passwords
      remoteRef:
        key: degoog-settings-passwords
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
