apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: degoog-data
  namespace: degoog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
