apiVersion: v1
kind: Service
metadata:
  name: degoog
  namespace: degoog
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.20.207
    kube-vip.io/ignore: "true"
spec:
  type: LoadBalancer
  selector:
    app: degoog
    component: web
  ports:
    - name: http
      port: 4444
      targetPort: http
      protocol: TCP
