apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-postgres-secret
  namespace: dispatcharr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dispatcharr-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dispatcharr-postgres-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-app-secret
  namespace: dispatcharr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dispatcharr-app-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: dispatcharr-secret-key
