apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-postgres-secret
  namespace: dispatcharr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dispatcharr-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dispatcharr-postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-app-secret
  namespace: dispatcharr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dispatcharr-app-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: secret-key
      remoteRef:
        key: dispatcharr-secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-vpn-secret
  namespace: dispatcharr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dispatcharr-vpn-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: wireguard-private-key
      remoteRef:
        key: dispatcharr-vpn-wireguard-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: wireguard-addresses
      remoteRef:
        key: dispatcharr-vpn-wireguard-address
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
