apiVersion: v1
kind: Service
metadata:
  name: dispatcharr
  namespace: dispatcharr
spec:
  selector:
    app: dispatcharr
    component: web
  ports:
    - name: http
      port: 9191
      targetPort: 9191
      protocol: TCP
