apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-exporter
  namespace: media-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: plex-exporter
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        key: plex-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: token
      remoteRef:
        key: plex-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
