apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dispatcharr
  namespace: dispatcharr
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: dispatcharr
      component: metrics
  namespaceSelector:
    matchNames:
      - dispatcharr
  endpoints:
    - port: metrics
      path: /metrics
