apiVersion: v1
kind: Service
metadata:
  name: network-syslog
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.20.203
  selector:
    app: syslog-ng
  ports:
    - name: syslog-udp
      port: 1514
      targetPort: 1514
      protocol: UDP
