apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: unpoller
  labels:
    app: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v3.3.1
          ports:
            - containerPort: 9130
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9130
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9130
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/unpoller/up.conf
              subPath: up.conf
      volumes:
        - name: config
          secret:
            secretName: unpoller-config
