apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller-config
  namespace: unpoller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: unpoller-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        up.conf: |
          [poller]
              debug = false
              quiet = false
              plugins = []
          [prometheus]
            disable = false
            http_listen = "0.0.0.0:9130"
            report_errors = false
          [influxdb]
            disable = true
          [loki]
            disable = true
          [unifi]
              dynamic = false
          [[unifi.controller]]
              url         = "https://10.1.10.2:11443"
              user        = "{{ .username }}"
              pass        = "{{ .password }}"
              sites       = ["all"]
              save_ids    = true
              save_dpi    = false
              save_sites  = true
              hash_pii    = false
              verify_ssl  = false
  data:
    - secretKey: username
      remoteRef:
        key: unpoller-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: unpoller-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
