apiVersion: v1
kind: Service
metadata:
  name: overseerr-exporter
  namespace: media-monitoring
  labels:
    app: overseerr-exporter
    component: metrics
spec:
  selector:
    app: overseerr-exporter
  ports:
    - name: metrics
      port: 9850
      targetPort: 9850
