apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: filesystem-trim-default
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: "0 2 * * *"
  groups:
    - default
  labels: {}
  name: filesystem-trim-default
  parameters: {}
  retain: 0
  task: filesystem-trim
