apiVersion: v1
kind: Service
metadata:
  name: opnsense-exporter
  namespace: monitoring
spec:
  selector:
    app: opnsense-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
