apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: opnsense-exporter-config
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: opnsense-exporter-api-key
    - secretKey: api-secret
      remoteRef:
        key: opnsense-exporter-api-secret
