apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dispatcharr-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: "16.7.27"
      helm:
        valueFiles:
          - $values/values/dispatcharr-postgresql.yaml
    - repoURL: https://github.com/slamanna212/HomelabArgoCD.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dispatcharr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
