apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guacamole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/slamanna212/HomelabArgoCD.git
    targetRevision: main
    path: workloads/guacamole
  destination:
    server: https://kubernetes.default.svc
    namespace: guacamole
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
