apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-mcp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/slamanna212/HomelabArgoCD.git
    targetRevision: main
    path: workloads/homelab-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
