apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-vpn-rules
  namespace: monitoring
  labels:
    loki_rule: "1"
data:
  vpn-alerts.yaml: |
    groups:
      - name: vpn
        interval: 1m
        rules:
          - alert: WireGuardVPNLogin
            expr: 'sum by (client, src) (count_over_time({job="network-syslog", vpn_event="VPN Client Connected"} | pattern `<_>src=<src> <_>suser=<client> <_>` [2m])) > 0'
            for: 0s
            labels:
              severity: warning
            annotations:
              summary: WireGuard VPN client connected
              description: '{{ $labels.client }} connected to WireGuard VPN from {{ $labels.src }}'
          - alert: WireGuardVPNDisconnect
            expr: 'sum by (client, duration, usage_down, usage_up) (count_over_time({job="network-syslog", vpn_event="VPN Client Disconnected"} | pattern `<_>suser=<client> <_>UNIFIduration=<duration> <_>UNIFIusageDown=<usage_down> <_>UNIFIusageUp=<usage_up> <_>` [2m])) > 0'
            for: 0s
            labels:
              severity: info
            annotations:
              summary: WireGuard VPN client disconnected
              description: '{{ $labels.client }} disconnected. Duration: {{ $labels.duration }}. Data: {{ $labels.usage_down }} down / {{ $labels.usage_up }} up'
