apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secrets
  namespace: hermes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: hermes-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: openrouter-api-key
      remoteRef:
        key: hermes-openrouter-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: discord-bot-token
      remoteRef:
        key: hermes-discord-bot-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: webui-password
      remoteRef:
        key: hermes-webui-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
