apiVersion: v1
kind: Service
metadata:
  name: exportarr-radarr
  namespace: media-monitoring
  labels:
    app: exportarr-radarr
    component: metrics
spec:
  selector:
    app: exportarr-radarr
  ports:
    - name: metrics
      port: 9707
      targetPort: 9707
