apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nzbhydra-exporter
  namespace: media-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: nzbhydra-exporter
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        key: nzbhydra-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: api-key
      remoteRef:
        key: nzbhydra-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
