apiVersion: v1
kind: Service
metadata:
  name: nzbhydra-exporter
  namespace: media-monitoring
  labels:
    app: nzbhydra-exporter
    component: metrics
spec:
  selector:
    app: nzbhydra-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
