apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: keyId
      remoteRef:
        key: b2-key-id
    - secretKey: appKey
      remoteRef:
        key: b2-app-key
    - secretKey: resticPassword
      remoteRef:
        key: b2-restic-password
